<?php

/**
 * @file
 * Savings Calculator module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function savings_calculator_theme() {
  return [
    'paragraph__savings_calculator' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function savings_calculator_preprocess_paragraph__savings_calculator(&$variables) {
  if ('preview' !== $variables['view_mode']) {
    $variables['#attached']['library'][] = 'savings_calculator/savings-calculator';
  }
}

/**
 * Implements hook_form_alter().
 */
function savings_calculator_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['field_paragraphs'])) {
    $form['#attached']['library'][] = 'savings_calculator/savings-calculator';
  }
}
