<?php

/**
 * @file
 * Code for campaign_pages module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function campaign_pages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the campain_pages module.
    case 'help.page.campaign_pages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Campaign pages functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function campaign_pages_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  // @fixme check for field Type, not name.
  $field_name = $context['items']->getFieldDefinition()->getName();

  // Change dropbuttons to normal list in Paragraphs inline forms.
  if ($field_name === 'field_paragraphs') {
    unset($element['top']['links']['#theme_wrappers']);
    $element['top']['links']['prefix']['#markup'] = '<ul class="paragraph-actions">';
  }

  // Changes to Menu field.
  if ($field_name === 'field_menu') {
    $element['uri']['#description'] = NULL;
    $element['uri']['#title_display'] = 'none';
    $element['title']['#title_display'] = 'none';
  }
}

/**
 * Implements hook_form_alter().
 */
function campaign_pages_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['node_campaign_form', 'node_campaign_edit_form'])) {
    // Menu: Change wording of Add more button.
    $form['field_menu']['widget']['add_more']['#value'] = t('New menu link');

    // Removes the "Add" word from the button values.
    // @todo Get actual display mode instead of default.
    $settings = entity_get_form_display('node', 'campaign', 'default')->getComponent('field_paragraphs')['settings'];
    if ($settings['add_mode'] === 'button') {
      // Add title to the section.
      $field_label = $form['field_paragraphs']['widget']['title']['#value'] ?? $form['field_paragraphs']['widget']['#title'];
      $form['field_paragraphs']['widget']['add_more']['title'] = [
        '#type' => 'table',
        '#header' => [t('Add @type', ['@type' => $field_label])],
        '#attributes' => [
          'class' => ['paragraphs-add-sections-title'],
        ],
        '#weight' => -1,
      ];

      if (isset($form['field_paragraphs']['widget']['add_more'])) {
        foreach ($form['field_paragraphs']['widget']['add_more'] as $key => &$item) {
          if (strpos($key, 'add_more_button_') === 0) {
            $arguments = $item['#value']->getArguments();
            // Adding a context, so it's translatable separatly.
            $options = ['context' => 'add_paragraph_type'];
            $item['#value'] = t('@type', $arguments, $options);
          }
        }
      }
    }

    // Set custom redirection callback to stay on the node form after submit.
    foreach (['submit', 'publish', 'unpublish'] as $action) {
      if (isset($form['actions'][$action])) {
        $form['actions'][$action]['#submit'][] = '_campaign_pages_disable_form_redirect';
      }
    }
  }
}

/**
 * Custom redirect for Campaign node submit.
 *
 * @param array &$form
 *   The form build array.
 * @param FormStateInterface $form_state
 *   The form state interface.
 */
function _campaign_pages_disable_form_redirect(&$form, FormStateInterface &$form_state) {
  // Sadly $form_state->disableRedirect() not works as expected, so we also
  // need to redirect to the edit form.
  // @todo Fix redirection of Content Moderation module
  // @see Drupal\content_moderation\EntityType
  $nid = $form_state->getValue('nid');
  $form_state->setRedirect('entity.node.edit_form', ['node' => $nid]);
}

/**
 * Implements hook_entity_operation_alter().
 */
function campaign_pages_entity_operation_alter(array &$operations, EntityInterface $entity) {
  // Remove `destination` URL query parameter on Operations
  // dropbutton for Campaign type nodes.
  if (method_exists($entity, 'getType') && $entity->getType() === 'campaign') {
    foreach ($operations as $operation => $data) {
      if (isset($data['query']['destination'])) {
        unset($operations[$operation]['query']['destination']);
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function campaign_pages_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__savings_calculator' => [
      'template' => 'paragraph--savings-calculator',
      'base hook' => 'paragraph'
    ]
  ];
}