<?php

/**
 * @file
 * Module file for the node_public_url module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function node_public_url_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.node_public_url':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enables generating public preview links for nodes') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function node_public_url_theme($existing, $type, $theme, $path) {
  return [
    'page__node__preview_links' => [
      'base hook' => 'page',
      'path' => $path . '/templates',
    ],
  ];
}
