<?php

/**
 * @file
 * Module file for the node_public_url module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function node_public_url_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.node_public_url':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enables generating public preview links for nodes') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function node_public_url_theme($existing, $type, $theme, $path) {
  return [
    'page__node__preview_links' => [
      'base hook' => 'page',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function node_public_url_node_delete(NodeInterface $node) {
  /** @var \Drupal\node_public_url\Storage\PathStorageInterface $storage */
  $storage = \Drupal::service('node_public_url.path_storage');
  $storage->delete(['nid' => $node->id()]);
}

/**
 * Implements hook_entity_translation_delete().
 */
function node_public_url_entity_translation_delete(EntityInterface $translation) {
  if ('node' === $translation->getEntityTypeId()) {
    /** @var \Drupal\node_public_url\Storage\PathStorageInterface $storage */
    $storage = \Drupal::service('node_public_url.path_storage');
    $storage->delete([
      'nid' => $translation->id(),
      'langcode' => $translation->language()->getId(),
    ]);
  }
}
