<?php

/**
 * @file
 * Code for Campaign Pages Tour module.
 */

// @todo: Maybe required some times.
// use Drupal\Core\Render\Element\HtmlTag;
//
// **
// * Implements hook_preprocess_HOOK().
// */
// function campaign_pages_tour_preprocess_page_title(&$variables) {
//  // Add Tour link to node.add pages.
//  if (\Drupal::currentUser()->hasPermission('access tour')) {
//    if (Drupal::routeMatch()->getRouteName() === 'node.add') {
//      // Create custom Tour button.
//      $tour_toggle = HtmlTag::preRenderHtmlTag([
//        '#tag' => 'button',
//        '#value' => '<span class="visually-hidden">' . t('Show help') . '</span>',
//        '#attributes' => [
//          'class' => 'tour-start',
//        ],
//        // This is needed for core tour.js to work...
//        '#prefix' => '<div class="campaign-pages-tour">',
//        '#suffix' => '</div>',
//      ]);
//
//      // Attach it after the title.
//      $variables['title_suffix'] = render($tour_toggle);
//
//      // Add a custom library to allow separate tour buttons.
// $variables['#attached']['library'] = ['elevation_tour/tour.extend'];
//    }
//  }
// }
